language: php
php:
  - 7.1
services:
  - mysql
before_install:
  - composer self-update
install: composer install --dev
before_script:
  - mysql -e 'create database activecollab_database_object_test'
script: vendor/bin/phpunit
