language: php
php:
  - 7.1
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
before_install:
  - composer self-update
install: composer install --dev
before_script:
  - mysql -e 'create database activecollab_database_object_test'
script: vendor/bin/phpunit
