dist: trusty
sudo: required
language: php
php:
  - 5.6
  - 7
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
mysql:
  database: activecollab_database_object_test
  username: root
  encoding: utf8mb4
before_install:
  - composer self-update
install: composer install --dev
before_script:
  - mysql -u root -e 'create database activecollab_database_object_test'
script: phpunit -c test/phpunit.xml
