sudo: true
language: php
php:
  - 7.1
services:
  - mysql
before_install:
  - composer self-update
install: composer install --dev
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e 'create database activecollab_database_object_test'
script: phpunit
